global:
  scrape_interval: 15s
  external_labels:
    monitor: 'vovetta-grpc-monitor'

scrape_configs:
  - job_name: 'python-grpc-server'
    scrape_interval: 5s
    static_configs:
      - targets:
        - python-grpc:1111

  - job_name: 'node-grpc-server'
    scrape_interval: 5s
    static_configs:
      - targets:
        -  node-grpc:1112